name: Autograding Tests
'on':
  push:
  workflow_dispatch:
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
    - name: check job execution
      id: check-job-execution
      run: |
        COMPLETED_RUNS=$(gh run list --repo ${{ github.repository }} --workflow 'Workflow Execution' --json conclusion)
        if echo "$COMPLETED_RUNS" | grep -q 'success'; then
          echo "result=success" >> $GITHUB_ENV
        else
          echo "result=failure" >> $GITHUB_ENV
        fi
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-JOB-EXECUTION_RESULTS: "${{ env.result }}"
        
      with:
        runners: check-job-execution