name: Workflow Execution
on: 
    workflow_dispatch:
        inputs:
            result:
                description: 'Debe funcionar correctamente?'
                type: choice
                options:
                    - SI
                    - NO
                default: SI
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build_status: ${{ steps.build.outputs.build_status == 'SI' && 'success' || 'failure' }}
        steps:      
            - name: 'Print GITHUB_OUTPUT path'       
              run: |
                echo "var -->> $GITHUB_OUTPUT"
            - name: Build
              id: build
              run: |
                echo "Building"
                echo "build_status=${{ inputs.result }}" >> "$GITHUB_OUTPUT"

    deploy:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ needs.build.outputs.build_status == 'success' }}    
      steps:      
        - name: Deploy                                     
          run: |
            echo "Deploying"
            echo "Deployment successful"

    rollback:
      runs-on: ubuntu-latest
      needs: build
      if: ${{ needs.build.outputs.build_status != 'success' }}    
      steps:      
          - name: Rollback                                     
            run: |
              echo "Rollback"
              exit 1
              - name: Check Rollback Condition
                run: |
                  if [[ "${{ needs.build.outputs.build_status }}" == "failure" ]]; then
                echo "Rollback condition met. Proceeding with rollback."
                  else
                echo "Rollback condition not met. Skipping rollback."
                exit 0